<a href="https://colab.research.google.com/github/Sornakala1031-m/Data-Analytics-using-python-Project/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def attendence(attended,total):
  return (attended/total)*100

attended = int(input("classes attended:"))
total = int(input("total classes:"))

percent = attendence(attended,total)

print("attentence percentage =",round(percent,2),"%")


classes attended:50
total classes:30
attentence percentage = 166.67 %


In [ ]:
import numpy as np

marks = np.array([85,79,53,49])

print(marks)


[85 79 53 49]


In [ ]:
import numpy as np

students = np.array([
    [85,79],
    [53,49],
    [39,29]
 ])
print(students)


[[85 79]
 [53 49]
 [39 29]]


In [ ]:
import numpy as np
arr = np.zeros((4,4))
print (arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
marks = np.array([45,78,93,29,65])
print(marks[2])

93


In [ ]:
import numpy as np
marks = np.array([45,78,93,29,65])
print(marks[0:4])

[45 78 93 29]
